Add / change files needed for python pkg distrib
rhinstaller/tclib pull request #12
Opened 2022-04-27 13:25 UTC by marta-lewandowska

Add setup.py, pyproject.toml which are necessary for python package
distribution using setuptools.
Change existing executables to suit packaging structure while
retaining present functionality.

2022-04-28 06:42 UTC, pholica commented on setup.py
> +        "Development Status :: 3 - Alpha",
The development status should be something representing production state (but not maintenance).

2022-04-28 06:57 UTC, pholica requested changes
Please fix the commented issues.

Also please use separate commit for moving the code from the scripts (`diff.py`, `query.py`, ...) to the tclib modules.

2022-04-28 06:57 UTC, pholica commented on setup.py
> +        "Development Status :: 3 - Alpha",
The development status should be something representing production state (but not maintenance).

2022-04-28 06:57 UTC, pholica commented on setup.py
> +    python_requires=">=2.7, <4",
Tclib is not meant to be used with python-2 so it should be removed from here and from the classifiers as well.

2022-04-28 06:57 UTC, pholica commented on setup.py
> +            "diff=tclib:diff_main.main",
The `diff` collides with `diff` from `diffutils` package. The query and validate names are also too generic for the command names (it's not clear they relate to tclib).

I'd suggest adding `tc` prefix resulting in `tcdiff`, `tcquery`, `tcvalidate` and possibly `tclib_generate_documents` as the short `tc` prefix doesn't make much sense in that case.

2022-04-28 12:54 UTC, velezd commented on setup.py
> +            "tc_diff=tclib:diff_main.main",
It would be better if you dropped the underscore -> tcdiff, tcquery...

2022-04-29 12:38 UTC, pholica requested changes
Please reduce the BuildRequires to have it as smallest as possible (let the RPM macros generate the BuildRequires and Requires)

2022-04-29 12:38 UTC, pholica commented on tclib.spec
> +BuildRequires:  git
I don't think git is required for building tclib rpm.

2022-04-29 12:38 UTC, pholica commented on tclib.spec
> +BuildRequires:  diffutils
Following packages are imho not needed for the build itself but rather for tests:

- diffutils
- python3-pylint

The question is if the tests that need those are called as part of %check and if %check is invoked during the build process. If not, then those packages are not needed for the build process.

I'd proceed keeping the BuildRequires as smallest as possible having there just only (if possible) following packages:

- python3-devel
- python3-sphinx
- python3-tox
- python3-wheel

As for the `python3-libxml2` it seems that this one got somehow forgotten (from other activities) and should not be here at all as the tclib doesn't depend on it in any way.

2022-04-29 12:38 UTC, pholica commented on tclib.spec
> +BuildRequires:  diffutils
Checking the docs of https://src.fedoraproject.org/rpms/pyproject-rpm-macros I can see that you should not need to care about the dependencies manually as they should be added by `%generate_buildrequires` and `%pyproject_buildrequires` so I guess it would make sense to have just only `BuildRequires: python3-devel`.

2022-05-02 06:56 UTC, marta-lewandowska commented
Finally got the build to work on epel-8 one painful push at a time :)
https://copr.fedorainfracloud.org/coprs/mlewando/tclib/builds/

2022-05-02 13:01 UTC, pholica approved these changes
Looks good, thank you. One thing that needs to be tested before merging is installing the built rpms on Fedora, epel-8 and epel-9 systems.

2022-05-03 05:42 UTC, pholica commented on tclib.spec
> +%if 0%{?rhel} < 9
It seems this doesn't have any effect on EPEL 8 in copr. Here are the requires of the built package there:
```
# rpm -q --requires -p python3-tclib-1.0.0-1.git.126.d7c4035.el8.noarch.rpm 
/usr/bin/python3.6
rpmlib(CompressedFileNames) <= 3.0.4-1
rpmlib(FileDigests) <= 4.6.0-1
rpmlib(PayloadFilesHavePrefix) <= 4.0-1
rpmlib(PayloadIsXz) <= 5.2-1
```

2022-05-03 07:44 UTC, pholica commented
There are still issues with EPEL 8:
```
# tcquery 
Traceback (most recent call last):
  File "/usr/bin/tcquery", line 11, in <module>
    load_entry_point('tclib==1.0.0', 'console_scripts', 'tcquery')()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 476, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2700, in load_entry_point
    return ep.load()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2318, in load
    return self.resolve()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2324, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
ModuleNotFoundError: No module named 'tclib'
# rpm -ql python3-tclib
/usr/bin/tc_generate_documents
/usr/bin/tcdiff
/usr/bin/tcquery
/usr/bin/tcvalidate
/usr/lib/python3.6/site-packages/tclib-1.0.0-py3.6.egg-info/PKG-INFO
/usr/lib/python3.6/site-packages/tclib-1.0.0-py3.6.egg-info/SOURCES.txt
/usr/lib/python3.6/site-packages/tclib-1.0.0-py3.6.egg-info/dependency_links.txt
/usr/lib/python3.6/site-packages/tclib-1.0.0-py3.6.egg-info/entry_points.txt
/usr/lib/python3.6/site-packages/tclib-1.0.0-py3.6.egg-info/requires.txt
/usr/lib/python3.6/site-packages/tclib-1.0.0-py3.6.egg-info/top_level.txt
/usr/share/doc/python3-tclib
/usr/share/doc/python3-tclib/README.md
```

2022-05-03 10:54 UTC, velezd approved these changes

2022-05-03 11:40 UTC, merged