Improved workflow
rhinstaller/tclib pull request #6
Opened 2022-02-04 15:18 UTC by velezd

2022-02-04 15:23 UTC, velezd commented
Running on fork without secrets https://github.com/velezd/tclib/pull/2

2022-02-07 06:23 UTC, pholica approved these changes
Looks good. Although it seems that there's a lot of extra instructions, I believe they are necessary and in the end serve the purpose. Thank you.

2022-02-07 06:25 UTC, pholica requested changes

2022-02-07 06:25 UTC, pholica commented on .github/workflows/pr_checks.yml
> +    if: needs.secrets-check.outputs.extra_tests_available == 'false'
It would make sense to me to have the base always executed no matter if secrets are set or not to make sure that the "vanilla" works even if the secrets are set.

2022-02-07 06:25 UTC, pholica commented on .github/workflows/pr_checks.yml
> +    if: needs.secrets-check.outputs.extra_tests_available == 'false'
I just realized that when I saw the base was skipped.

2022-02-07 08:01 UTC, velezd commented on .github/workflows/pr_checks.yml
> +    if: needs.secrets-check.outputs.extra_tests_available == 'false'
Extended also executes tests from base

2022-02-07 09:35 UTC, pholica commented on .github/workflows/pr_checks.yml
> +    if: needs.secrets-check.outputs.extra_tests_available == 'false'
Thank you for enabling the base test unconditionally (even though they may contain subset of the extended tests).

2022-02-07 09:35 UTC, pholica approved these changes
Looks good now, Thank you.

2022-02-07 09:36 UTC, merged